Update firewalld resource to include more properties
mitre/inspec pull request #13
Opened 2021-07-08 21:27 UTC by dtingstrom

I needed to retrieve the target of an active firewall zone and noticed that the target and some other properties were missing from the firewalld resource. So I added these 9 properties:
1. target
2. icmp_block_inversion
3. ports
4. protocols
5. masquerade
6. forward_ports
7. source_ports
8. icmp_blocks
9. rich_rules

I also created mock tests for all the new properties.

Signed-off-by: Daniel Tingstrom <dtingstrom@mitre.org>

2021-07-08 21:33 UTC, aaronlippold requested changes
Please add a `?` at the end of the function as this is a boolean per ruby standard conventions.

2021-07-08 21:33 UTC, aaronlippold commented on lib/inspec/resources/firewalld.rb
> +    def icmp_block_inversion_bound(query_zone)
Please add a `?` at the end of the function as this is a boolean per ruby standard conventions.

2021-07-08 21:33 UTC, aaronlippold commented on lib/inspec/resources/firewalld.rb
> +    def masquerade_bound(query_zone)
Please add a ? at the end of the function as this is a boolean per ruby standard conventions.

2021-07-09 18:59 UTC, closed without merging

2021-07-09 18:59 UTC, wdower commented
Reopening against inspec/inspec.